package exception_handling;

public class Exception {

	public static void main(String[] args) {
		
	//try {	int x = 10;
        //int y = 0  ;
        //int result = x/y;
        //System.out.println("Resul: " + result);
        
	//}catch(IndexOutOfBoundsException  e1) {
		//System.out.println("Exception " + e1);
	  
	//}catch(ArithmeticException e) {
		//System.out.println("Exception: " + e);
	//}	
	//finally{
       // System.out.println("It is solved by Ila and Ritu");
	//}

		
		
		
   }
}